### ISSUE TITLE
setup JUnit

### ISSUE THREAD

**Issue by janniezhong** [adamstorek/aswe-proj#3]
Research/setup a basic test framework

- does junit have both unit + integration tests?
- does junit have mocking?

**Comment by adamstorek** [comment]
Spring Boot tester comes with JUnit for unit testing, Mockito for mocking, and also provides classes for integration testing (see https://www.baeldung.com/spring-boot-testing, https://docs.spring.io/spring-boot/docs/current/api/index.html?org/springframework/boot/test/context/SpringBootTest.html).
