### ISSUE TITLE
setup databases + accessibility in java spring (JDBC?)

### ISSUE THREAD

**Issue by janniezhong** [adamstorek/aswe-proj#4]
- 1 table with beacons + beacon data
    - Beacon id (primary id)
    - User id (that this beacon belongs to)
- 1 table with users + user data (store this in a separate authentication)	
    - User id (primary key)
    - username
    - user password hash  (**do we need this for this week?**)
    - password salt (^)
    - Beacon list
- 1 table for commands
    - Command id (primary key)
    - Beacon id (also primary key, foreign key for beacon (duh))
    - Has been sent to beacon (bool)
    - Has been executed by beacon? (boolean)

**Comment by adamstorek** [comment]
The database container is now accessible from Spring Boot.

**Comment by adamstorek** [comment]
- 1 table with beacons + beacon data
    - beacon id (primary id) - unique
    - beaconName (used by the user - owner_username and beaconName combo should be unique)
    - ~~User id (that this beacon belongs to)~~
    - owner_username (might make it easier for us to add additional users in the future)
- 1 table with users + user data (store this in a separate authentication)	
    - ~~User id (primary key)~~
    - username (primary id)
    - user password (Bcrypt has one string for both password hash and salt)
    - Beacon list
- 1 table for commands
    - Command id (primary id)
    - Beacon name (also primary key, foreign key for beacon (duh))
    - Status (string enum: "pending" (just added by the user), "sent" (sent to beacon), "executed" (result sent back by the beacon), "finished" (result sent back to user))

**Comment by adamstorek** [comment]
Finished.
